### ISSUE TITLE
Guard plugin

### ISSUE THREAD

**Issue by Frexuz** [kddeisz/snip_snip#1]
Would be badass to have it output in [Guard](https://github.com/guard/guard) :P

**Comment by kddeisz** [comment]
Interesting! I'm not entirely sure when it would output. If a controller/model/etc changes does it try run something?

**Comment by Frexuz** [comment]
I guess it could listen on the log file, and output that? :)

If not, maybe a mini web UI, like **Bullet** or **rack-mini-profiler** :)

Just some thoughts.
